# This Ansible playbook updates and upgrades packages on a group of Ubuntu servers.
# It connects to the 'Ubuntu' group and executes tasks as a sudo user for privilege escalation.
# The playbook first updates the package lists on the servers using the 'apt' module.
# Then, it performs a distribution upgrade, removing any unused packages and cleaning the package cache.
# Please ensure SSH access and appropriate permissions are set up for executing the tasks.

---
- hosts: ubuntu_servers
  gather_facts: yes
  become: yes
  become_method: sudo
  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Enter sudo password"
      private: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages.
      apt:
        upgrade: dist

    - name: Check if reboot required.
      stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot Servers if required.
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies no longer required.
      apt:
        autoremove: yes
        autoclean: yes